### PR TITLE
fix: await bundle finish before open browser url to prevent a 404 page

### PR DESCRIPTION
**Pull request by danielbarion**
This PR's fix the 404 page in the first view of the application.

### CODE REVIEW

**Comment by paclaraujo** [comment]
@danielbarion Very nice! Good job! I'm having this problem!

**Comment by 4lejandrito** [comment]
Hi @danielbarion,

Thanks for you pull request. 

Can you please provide some instructions on how to reproduce the issue? Maybe a sample project that I can download to reproduce it myself? 

By the way, tests are running fine both on [GitHub Actions](https://github.com/4lejandrito/rollup-plugin-browsersync/runs/881614810?check_suite_focus=true) and locally for me using `node@v14.9.0`. Which version are you using?

If I run the tests with your changes they fail. I believe that is because you have removed the line that actually tells browsersync to reload every time there is a change:

```
bs.reload(bundle.dest);
```

I would appreciate if you could update the pull request so that the tests pass with your changes.

**Comment by 4lejandrito** [comment]
I've published a new version using `writeBundle`. I don't think it will resolve your issue but it is indeed more correct (see https://github.com/4lejandrito/rollup-plugin-browsersync/commit/b20db01009b61943e9a018db49651419c9007ccf).

**Comment by 4lejandrito** [comment]
Hi again @danielbarion,

I have published a prerelease (1.3.0-alpha.1) with a change that could fix your issue. Can you please confirm?

```
npm i rollup-plugin-browsersync@1.3.0-alpha.1
```

**Comment by danielbarion** [comment]
Hey @4lejandrito!
I'll take a look into this alpha version, thank you!

I'm using Node v13.13.0.

I'll provide a test repository in few minutes

**Comment by danielbarion** [comment]
The example with the "error" (the plugin opens the browser window before the bundle finish)

https://github.com/danielbarion/browsersync-example/

Yeah, the alpha version works as expected! Thank you!

Here is the Alpha version branch:

https://github.com/danielbarion/browsersync-example/pull/1

**Comment by 4lejandrito** [comment]
Thanks a lot! It failed with the current version and worked with the alpha. 

I just published `1.3.0` so you can start using it now. 

I am closing this pull request.

Thanks for reporting it.

**Comment by 4lejandrito** [comment]
Fixed by https://github.com/4lejandrito/rollup-plugin-browsersync/commit/1f2265b610532e848d414c124c4c4f1f13fdc4ff.

**Pull request closed without merging**
